### ISSUE TITLE
QT Creator Setup

### ISSUE THREAD

**Issue by lordqwerty** [Open-TEE/project#11]
Hello,

I have noticed on your slides titled "Open-TEE – A Virtual Trusted Execution Environment" it shows screenshots of the project code running in QT Creator. I'm trying to get it to run in QT Creator, is there any documentation I'm missing somewhere for this? 

If not could I get some help in setting this up or links that might help me do so? 

Cheers,
Jorden

**Comment by brianmcgillion** [comment]
Hi Jorden,

After a full repo sync of the Open-TEE directory. I just run:
Open-TEE $ qtcreator project.qbs &

Then bottom left of the qtcreator window select the project you want to run
to be  opentee-engine.

Then you need to edit your /etc/opentee.conf file to have something similar
to the following:

$ cat /etc/opentee.conf
[PATHS]
ta_dir_path =
/home/brian/code/ccpp/build-project-Desktop-Debug/qtc_Desktop_7bb86f62-debug/TAs
core_lib_path =
/home/brian/code/ccpp/build-project-Desktop-Debug/qtc_Desktop_7bb86f62-debug
opentee_bin =
/home/brian/code/ccpp/build-project-Desktop-Debug/qtc_Desktop_7bb86f62-debug/opentee-engine
#ta_dir_path = /home/brian/code/ccpp/Open-TEE/gcc-debug/TAs
#core_lib_path = /home/brian/code/ccpp/Open-TEE/gcc-debug
#opentee_bin = /home/brian/code/ccpp/Open-TEE/gcc-debug/opentee-engine
subprocess_manager = libManagerApi.so
subprocess_launcher = libLauncherApi.so


As you can see the first 3 entries need to point towards the build path
where creator is dumping the output.

Then when you run the project it should run just fine. We have seen a
problem with newer versions of QtCreator not following the child process
after the fork, we have yet to determine the cause. I encountered the
similar problem with another project the other day, but I have not had time
to resolve it yet. Older versions worked just fine.

Br,
Brian

**Comment by TanelDettenborn** [comment]
If the Qt Creator is not parsing the Qbs project: In QT Creator: Help ->
About Plugins -> Select QbsProjectManager box
At least at older version this was not a default setting..

-Tanel

2015-10-06 14:15 GMT+03:00 Brian McGillion <notifications@github.com>:

**Comment by lordqwerty** [comment]
Thank you both very much for your speedy responses. 
@brianmcgillion I am trying the method you described but when parsing the qbs project file it gives me the following error: 

`/home/jorden/Android/Open-TEE/project/qbs/modules/OpenSSL/OpenSSL.qbs:3: error: Items of type 'Module' cannot contain items of type 'Probe'.`

I also assume it is for this reason that I don't get the choice to run the opentee-engine. Sorry I'm a newbie to QT Creator and well TEE's in general. Really excited to get started in using and understanding TEE's.

Thanks for your time.  

![screenshot from 2015-10-06 12 31 26](https://cloud.githubusercontent.com/assets/1949133/10307364/3a25b7f6-6c26-11e5-9515-b14c8171dc94.png)

**Comment by brianmcgillion** [comment]
What version of QtCreator are you running there ?

**Comment by lordqwerty** [comment]
QT Creator 3.1.1
QBS 1.5.0

**Comment by brianmcgillion** [comment]
There has been quite heavy development with qbs recently, and especially
the one bundled with qtcreator, so I would suggest that you take the latest
stable qtcreator which is at version 3.5:

 http://www.qt.io/download-open-source/

**Comment by lordqwerty** [comment]
Hello Brian,

Thank you so much this has solved the problem and I can now build it in QtCreator.
