### ISSUE TITLE
How to use storage_test.c and crypto_test.c in the Test?

### ISSUE THREAD

**Issue by DC-Zhou** [Open-TEE/project#13]
Because I is new to this project. I think some time have to use storage functions or crypto functions  in other side .  would you please tell me how to use those functions just in other side (such as just do storage  write , read operation  in a program)  Thank you for your help

**Comment by brianmcgillion** [comment]
If you look at the tests project you will see that crypto_test and storage_test are created as dynamic libraries. Under TrustedApplications > ta_conn_test_app > ta_conn_test_app.qbs you will see that those are linked into this test TA. Looking at ta_conn_test_app.c you will see that the storage_test and crypto_test functions are called in a number of places here.

**Comment by brianmcgillion** [comment]
I hope that is what you were looking for.
