### ISSUE TITLE
The link in the tutorial subsection "Using the QtCreator IDE" has a page not found error.

### ISSUE THREAD

**Issue by YangRongAtGit** [Open-TEE/project#14]
Hello, 

When I tried the link "QtCreator Usage" in the tutorial. I got an error "404 file not found" error. Can some one fix this problem?

Thanks,

Rong

**Comment by lordqwerty** [comment]
In the meantime you can see the MD document for it.

https://github.com/Open-TEE/Open-Tee.github.io/blob/master/_posts/2015-10-10-qtcreator.md

**Comment by YangRongAtGit** [comment]
- Qt version 4.8
- Ubuntu 16.04 TLS

The Ubuntu I am using without Qt installed. By following the guide I had following errors:
_void DBusMenuExporterPrivate::addAction(QAction*, int): Already tracking action "Follow Symbol Under Cursor" under id 173_

The cause of the problem is Qt SDK is missing. Even the Qt SDK gets installed afterward, the path of some *.prl files are installed in the Qt folder. But the QtCreator is searching in different folder. The way I fix the problem is to remove the QtCreator and install the Qt SDK. After that re-install QtCreator again.


Removing the QtCreator by running the command 
_./MaintenanceTool_
from the Qt install folder.

After QtCreator is uninstalled. The Qt SDK need to be installed by using the following command.
_sudo apt-get install qt-sdk_

After the SDK is installed. I followed the guide to re-install the QtCreator. Then everything is fine.
