### ISSUE TITLE
Unable to load a shared TA library with error Segmentation fault (Signal SIGSEGV) after added libraries OpenCV and relic

### ISSUE THREAD

**Issue by YangRongAtGit** [Open-TEE/project#18]
Hello Open-TEE devs,

I asked the same question by sent an email to the mailing list. The email was unable to be delivered. Trying to yield on the freenode, but seems no one respond. So I back to here again.

I am working on a research project in the university of Auckland. We are using the Open-TEE framework.

Currently, I am trying to use the open-cv and an encryption library called relic in the trusted environment. But when the system to load the shared library, it reports a segmentation fault error. If I excluded the opencv and relic libraries, the TA library can be loaded successfully.  

-----------------------------------------------------------------------------------------------------

The way I include the library is in the sfc.qbs file. 
For the set libraries: 
1. For shared libraries, The *.so path are added into /etc/ld.so.conf.d/ and sudo ldconfig is executed.
2. For static library, relic, the -fPIC option is added when compiling.

I added library settings into the TA's qbs config file:

`cpp.cxxLanguageVersion:"c++11"`
`cpp.warningLevel:"none" // both of those libraries have some warnings`
`cpp.includePaths: ["../include"
    , "/path_of_relic/include"
    , "/usr/local/include/opencv" 
]`
`cpp.libraryPaths: ["path_relic"
        , "path_opencv"
   ]`
`cpp.staticLibraries: ["relic_pic"
        , "opencv_core"
        , "opencv_imgcodecs"
        , "opencv_highgui"
        , "opencv_imgproc"
    ]`

I also tried to include the shared opencv shared libraries:

`cpp.dynamicLibraries: ['opencv_core'
        , 'opencv_imgcodecs'
        , 'opencv_highgui'
        , 'opencv_imgproc'
    ]`

but I had same problem - the TA library libta_scf.so got rejected.

-----------------------------------------------------------------------------------------------------

I checked the syslog, the log is:

>~~~Jul 19 15:55:09 Lulu tee_manager:
/home/r0ng/tools/OpenTEE/emulator/manager/ta_dir_watch.c:add_new_ta:201  libta_scf.so : properties section is not found
Jul 19 15:55:09 Lulu tee_manager: /home/r0ng/tools/OpenTEE/emulator/manager/ta_dir_watch.c:add_new_ta:227  TA "libta_scf.so" rejected~~~
Jul 20 12:05:08 Lulu kernel: [ 7125.177214] libta_scf.so[808]: segfault at 31a ip 00007f2b54935d43 sp 00000000018a99a0 error 4 in ld-2.23.so[7f2b5492c000+26000]

-----------------------------------------------------------------------------------------------------

The debugger log provides more info (see the bold italic text), but I still unable to figure out the cause of the TA library got rejected. 

> --- token barrier ---
dNOTE: INFERIOR RUN REQUESTED
sRun requested...
dState changed from InferiorStopOk(14) to InferiorRunRequested(10) [master]
sStep next requested...
1087-exec-next
1087^running
dNOTE: INFERIOR RUN OK
sRunning.
dState changed from InferiorRunRequested(10) to InferiorRunOk(11) [master]
*running,thread-id="all"
dNOTE: INFERIOR STILL RUNNING IN STATE InferiorRunOk.

>
**_~"\nThread "
~"2.1 \"libta_scf.so\" received signal SIGSEGV, Segmentation fault.\n"
~"do_lookup_x (undef_name=undef_name@entry=0x7f7bceaa18f8 \"_ITM_deregisterTMCloneTable\", new_hash=new_hash@entry=2247416213, old_hash=old_hash@entry=0x706b80, ref=0x7f7bceaa1390, result=result@entry=0x706b90, scope=<optimized out>, i=0, version=0x0, flags=1, skip=0x0, type_class=4, undef_map=0x7188d0) at dl-lookup.c:377\n"
>&"377\tdl-lookup.c: No such file or directory.\n"
>*stopped,reason="signal-received",signal-name="SIGSEGV",signal-meaning="Segmentation fault",frame={addr="0x00007f7bd9d7bd43",func="do_lookup_x",args=[{name="undef_name",value="0x7f7bceaa18f8 \"_ITM_deregisterTMCloneTable\""},{name="undef_name@entry",value="0x7f7bceaa18f8 \"_ITM_deregisterTMCloneTable\""},{name="new_hash",value="2247416213"},{name="new_hash@entry",value="2247416213"},{name="old_hash",value="0x706b80"},{name="old_hash@entry",value="0x706b80"},{name="ref",value="0x7f7bceaa1390"},{name="result",value="0x706b90"},{name="result@entry",value="0x706b90"},{name="scope",value="<optimized out>"},{name="i",value="0"},{name="version",value="0x0"},{name="flags",value="1"},{name="skip",value="0x0"},{name="type_class",value="4"},{name="undef_map",value="0x7188d0"}],file="dl-lookup.c",fullname="/build/glibc-GKVZIf/glibc-2.23/elf/dl-lookup.c",line="377"},thread-id="2",stopped-threads="all",core="2"
dNOTE: INFERIOR SPONTANEOUS STOP
sStopped.
dState changed from InferiorRunOk(11) to InferiorStopOk(14) [master]
dHANDLING SIGNAL SIGSEGV
sStopped: Segmentation fault (Signal SIGSEGV)._**

>
1088-thread-info
1088^done,threads=[{id="2",target-id="Thread 0x7f7bd9f74700 (LWP 17461)",name="libta_scf.so",frame={level="0",addr="0x00007f7bd9d7bd43",func="do_lookup_x",args=[{name="undef_name",value="0x7f7bceaa18f8 \"_ITM_deregisterTMCloneTable\""},{name="undef_name@entry",value="0x7f7bceaa18f8 \"_ITM_deregisterTMCloneTable\""},{name="new_hash",value="2247416213"},{name="new_hash@entry",value="2247416213"},{name="old_hash",value="0x706b80"},{name="old_hash@entry",value="0x706b80"},{name="ref",value="0x7f7bceaa1390"},{name="result",value="0x706b90"},{name="result@entry",value="0x706b90"},{name="scope",value="<optimized out>"},{name="i",value="0"},{name="version",value="0x0"},{name="flags",value="1"},{name="skip",value="0x0"},{name="type_class",value="4"},{name="undef_map",value="0x7188d0"}],file="dl-lookup.c",fullname="/build/glibc-GKVZIf/glibc-2.23/elf/dl-lookup.c",line="377"},state="stopped",core="2"}],current-thread-id="2"
-1089threadnames 20
-1090python theDumper.fetchStack({"limit":20,"nativemixed":0,"token":1090})

>
&"threadnames 20\n"
~"[]\n"
1089^done

>
&"python theDumper.fetchStack({\"limit\":20,\"nativemixed\":0,\"token\":1090})\n"
~"frames=[frame={level=\"0\",address=\"0x7f7bd9d7bd43\",function=\"do_lookup_x\",file=\"/build/glibc-GKVZIf/glibc-2.23/elf/dl-lookup.c\",line=\"377\",module=\"/usr/lib/debug/lib/x86_64-linux-gnu/ld-2.23.so\",language=\"c\"},frame={level=\"1\",address=\"0x7f7bd9d7c94f\",function=\"_dl_lookup_symbol_x\",file=\"/build/glibc-GKVZIf/glibc-2.23/elf/dl-lookup.c\",line=\"829\",module=\"/usr/lib/debug/lib/x86_64-linux-gnu/ld-2.23.so\",language=\"c\"},frame={level=\"2\",address=\"0x7f7bd9d7e5ad\",function=\"elf_machine_rela\",file=\"/build/glibc-GKVZIf/glibc-2.23/elf/../sysdeps/x86_64/dl-machine.h\",line=\"301\",module=\"/usr/lib/debug/lib/x86_64-linux-gnu/ld-2.23.so\",language=\"c\"},frame={level=\"3\",address=\"0x7f7bd9d7e5ad\",function=\"elf_dynamic_do_Rela\",file=\"/build/glibc-GKVZIf/glibc-2.23/elf/do-rel.h\",line=\"137\",module=\"/usr/lib/debug/lib/x86_64-linux-gnu/ld-2.23.so\",language=\"c\"},frame={level=\"4\",address=\"0x7f7bd9d7e5ad\",function=\"_dl_relocate_object\",file=\"/build/glibc-GKVZIf/glibc-2.23/elf/dl-reloc.c\",line=\"258\",module=\"/usr/lib/debug/lib/x86_64-linux-gnu/ld-2.23.so\",language=\"c\"},frame={level=\"5\",address=\"0x7f7bd9d87681\",function=\"dl_open_worker\",file=\"/build/glibc-GKVZIf/glibc-2.23/elf/dl-open.c\",line=\"435\",module=\"/usr/lib/debug/lib/x86_64-linux-gnu/ld-2.23.so\",language=\"c\"},frame={level=\"6\",address=\"0x7f7bd9d82394\",function=\"_dl_catch_error\",file=\"/build/glibc-GKVZIf/glibc-2.23/elf/dl-error.c\",line=\"187\",module=\"/usr/lib/debug/lib/x86_64-linux-gnu/ld-2.23.so\",language=\"c\"},frame={level=\"7\",address=\"0x7f7bd9d86bd9\",function=\"_dl_open\",file=\"/build/glibc-GKVZIf/glibc-2.23/elf/dl-open.c\",line=\"660\",module=\"/usr/lib/debug/lib/x86_64-linux-gnu/ld-2.23.so\",language=\"c\"},frame={level=\"8\",address=\"0x7f7bd9b6ef09\",function=\"dlopen_doit\",file=\"/build/glibc-GKVZIf/glibc-2.23/dlfcn/dlopen.c\",line=\"66\",module=\"/usr/lib/debug/lib/x86_64-linux-gnu/libdl-2.23.so\",language=\"c\"},frame={level=\"9\",address=\"0x7f7bd9d82394\",function=\"_dl_catch_error\",file=\"/build/glibc-GKVZIf/glibc-2.23/elf/dl-error.c\",line=\"187\",module=\"/usr/lib/debug/lib/x86_64-linux-gnu/ld-2.23.so\",language=\"c\"},frame={level=\"10\",address=\"0x7f7bd9b6f571\",function=\"_dlerror_run\",file=\"/build/glibc-GKVZIf/glibc-2.23/dlfcn/dlerror.c\",line=\"163\",module=\"/usr/lib/debug/lib/x86_64-linux-gnu/libdl-2.23.so\",language=\"c\"},frame={level=\"11\",address=\"0x7f7bd9b6efa1\",function=\"__dlopen\",file=\"/build/glibc-GKVZIf/glibc-2.23/dlfcn/dlopen.c\",line=\"87\",module=\"/usr/lib/debug/lib/x86_64-linux-gnu/libdl-2.23.so\",language=\"c\"},frame={level=\"12\",address=\"0x7f7bd937f174\",function=\"load_ta\",file=\"/home/r0ng/tools/OpenTEE/emulator/launcher/dynamic_loader.c\",line=\"53\",module=\"/home/r0ng/tools/OpenTEE/debug/libLauncherApi.so\",language=\"c\"},frame={level=\"13\",address=\"0x7f7bd9383c47\",function=\"ta_process_loop\",file=\"/home/r0ng/tools/OpenTEE/emulator/launcher/ta_process.c\",line=\"161\",module=\"/home/r0ng/tools/OpenTEE/debug/libLauncherApi.so\",language=\"c\"},frame={level=\"14\",address=\"0x7f7bd968eb5d\",function=\"clone\",file=\"/build/glibc-GKVZIf/glibc-2.23/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S\",line=\"109\",module=\"/usr/lib/debug/lib/x86_64-linux-gnu/libc-2.23.so\",language=\"c\"}]\n"
1090^done
1091-stack-select-frame 12
1092python theDumper.fetchVariables({"autoderef":1,"context":"","displaystringlimit":"100","dyntype":1,"expanded":["inspect","local","return","watch"],"fancy":1,"formats":{},"nativemixed":0,"partialvar":"","passexceptions":0,"qobjectnames":0,"resultvarname":"","stringcutoff":"10000","token":1092,"typeformats":{},"watchers":[{"exp":"70617273655f746565635f726573756c7428726573756c7429","iname":"watch.0"},{"exp":"2a73657373696f6e436f6e74657874","iname":"watch.1"},{"exp":"28636861722a2970617468","iname":"watch.2"}]})

>
1091^done

>
&"python theDumper.fetchVariables({\"autoderef\":1,\"context\":\"\",\"displaystringlimit\":\"100\",\"dyntype\":1,\"expanded\":[\"inspect\",\"local\",\"return\",\"watch\"],\"fancy\":1,\"formats\":{},\"nativemixed\":0,\"partialvar\":\"\",\"passexceptions\":0,\"qobjectnames\":0,\"resultvarname\":\"\",\"stringcutoff\":\"10000\",\"token\":1092,\"typeformats\":{},\"watchers\":[{\"exp\":\"70617273655f746565635f726573756c7428726573756c7429\",\"iname\":\"watch.0\"},{\"exp\":\"2a73657373696f6e436f6e74657874\",\"iname\":\"watch.1\"},{\"exp\":\"28636861722a2970617468\",\"iname\":\"watch.2\"}]})\n"
>~"data=[{iname=\"local.path\",name=\"path\",origaddr=\"0x707398\",numchild=\"0\",type=\"char *\",valueencoded=\"utf8\",value=\"2F686F6D652F72306E672F746F6F6C732F4F70656E5445452F64656275672F5441732F6C696274615F7363662E736F\",address=\"0x7075b0\",},{iname=\"local.callbacks\",name=\"callbacks\",origaddr=\"0x707390\",numchild=\"0\",origaddr=\"0x707390\",type=\"ta_interface *\",value=\"0x0\",address=\"0x7f7bd95873a0\",},{iname=\"local.tmp_cb\",name=\"tmp_cb\",numchild=\"7\",type=\"ta_interface\",value=\"\",address=\"0x7073f0\",},{iname=\"local.err\",name=\"err\",numchild=\"0\",type=\"char *\",value=\"0x0\",address=\"0x7073a8\",},{iname=\"local.internal_api_calls\",name=\"internal_api_calls\",numchild=\"7\",type=\"internal_api_callbacks\",value=\"\",address=\"0x7073b0\",},{iname=\"local.__func__\",name=\"__func__\",numchild=\"8\",type=\"char [8]\",valueencoded=\"utf8\",value=\"6C6F61645F746100\",address=\"0x7f7bd93843f8\",},{iname=\"watch.0\",wname=\"70617273655F746565635F726573756C7428726573756C7429\",numchild=\"0\",type=\" \",value=\"<no such value>\",},{iname=\"watch.1\",wname=\"2A73657373696F6E436F6E74657874\",numchild=\"0\",type=\" \",value=\"<no such value>\",},{iname=\"watch.2\",wname=\"28636861722A2970617468\",origaddr=\"0x707398\",numchild=\"0\",type=\"char *\",valueencoded=\"utf8\",value=\"2F686F6D652F72306E672F746F6F6C732F4F70656E5445452F64656275672F5441732F6C696274615F7363662E736F\",address=\"0x7075b0\",},],typeinfo=[],partial=\"0\"\n"
1092^done
 Rebuild Watchmodel 55 @ 16:29:39.914 [20601ms] 
sFinished retrieving data

-----------------------------------------------------------------------------------------------------

Could anyone enlight me and let me what am I missed?

Thanks in advance

r0nG

**Comment by TanelDettenborn** [comment]
Hi r0nG,

I am guessing that you are not writing the TA property section to TA
binary. Make sure you are doing one of these at our TA:
-For examle make something like open_tee_conf.c file and include that into
compiling: https://github.com/Open-TEE/TAs/tree/master/example_ta
-Or use SET_TA_PROPERTIES -macro directly at our TA source files:
https://github.com/Open-TEE/TAs/blob/master/example_digest_ta/example_digest_ta.c

Please let me know if this helps. If not then we can debug some more :)

-Tanel

2016-07-19 6:27 GMT+01:00 r0nG <notifications@github.com>:

**Comment by YangRongAtGit** [comment]
Hello TanelDettenborn,

Thanks for your reply. I defined an uuid in a common header file:
`#define SCF_UUID {0x123A567B, 0xB765, 0xA321, { 'B', 'I', 'G', 'E', 'S', 'T', '0', '0'}}`

In the ta_scf.cpp

`#ifdef TA_PLUGIN
#include "tee_ta_properties.h" /* Setting TA properties */`

`/* UUID must be unique */`
`SET_TA_PROPERTIES(`
`    SCF_UUID,`
`    512,  // dataSize`
`    255,  // stackSize`
`    1,    // singletonInstance`
`    1,    // multiSession`
`    1)    // instanceKeepAlive`
`#endif // TA_PLUGIN`
`} // extern "C"`

I also mentioned that if I removed opencv and relic libraries, the CA and TA works fine. So I do not think the segmentation fault is caused by property settings.


Thanks,

**Comment by TanelDettenborn** [comment]
I am a bit puzzeled, because of the syslog. It is stating that propertie
section is not found, but you are receiving a segfault.. If I may ask,
could you search the propertie section from our TA binary after
compilation? E.g. "readelf -S our_ta_elf | grep .ta_properties".

-Tanel

2016-07-19 13:22 GMT+01:00 r0nG <notifications@github.com>:

**Comment by YangRongAtGit** [comment]
Hello Tanel,

I run the cmd in Open-TEE/debug:

`readelf -S libta_scf.so | grep .ta_properties`

The result is:

`[25] .ta_properties    PROGBITS         00000000002ac720  000ac720`

Is that mean I grabbed an incorrect syslog?

**Comment by brianmcgillion** [comment]
Hi,

The log message that you posted:

Jul 19 15:55:09 Lulu tee_manager:
/home/r0ng/tools/OpenTEE/emulator/manager/ta_dir_watch.c:add_new_ta:201
libta_scf.so : properties section is not found
Jul 19 15:55:09 Lulu tee_manager:
/home/r0ng/tools/OpenTEE/emulator/manager/ta_dir_watch.c:add_new_ta:227 TA
"libta_scf.so" rejected

Implies as Tanel said that the properties section seems not to be found.
But that should not cause a seg fault, it should print the warning and then
when a client tries to connect tot the TA you should get an error
indicating that the TA could not be found.

Looking at your make file it seems that you are mixing c and c++
(cpp.cxxLanguageVersion:"c++11"). The GP API is a C API so none of our
internal functionality is wrapped by

*extern "C" {}*

This means that c++ name mangling is an issue and as such this will cause
problems in dlopen and friends, which are written with C in mind.

It is true that the libtee client facing API could be wrapped in those
blocks to allow calling from C++ CAs, but internally this was never
conceived.

Can you give the output from straight from GDB after running the TA and it
seg faulting? On the GDB cmdline run: "thread apply all bt". Are the
libraries that you are trying to load c++ or C libraries?

Thanks,
Brian

**Comment by YangRongAtGit** [comment]
Hello Brian&Tanel,

Thanks for the help. I found the code that cause of the problem just now. But I have not figure out reason.

The opencv library highgui is used in the shared library TA libta_scf.so. My teammate wrot code:

``` c++
namedWindow("Show result", WINDOW_AUTOSIZE );
imshow("Show result", data);
waitKey(0);
```

to create a window for the debugging purpose.

I know on OSX or Windows, all GUI related code must run in the main thread. Not sure the GUI rule on Ubuntu. Plus the TA is running on a separate process. Maybe, to invoke GUI code is not a good idea.

If you have any idea about what might cause the problem, please let me know. In the meantime, I will keep investigating the cause of the issue.

-------------------------------------------------------------------------------------------------------------------------

As to the issue of the shared library rejected. I found that I need to kill/restart the manager/launcher processes after modified the TA. Sometimes I forgot to do that. Maybe I need some pre-build scripts to reset manager/launcher process, I know that is possible in visual studio but do think that is possible in qt creator.

-------------------------------------------------------------------------------------------------------------------------

Thank you very much,

r0nG

**Comment by YangRongAtGit** [comment]
Maybe the framework could provide some extern interfaces so developers could create GUI for TA. Thanks for the helps :)
