### ISSUE TITLE
'OpenSSL' not found for profile 'gcc'

### ISSUE THREAD

**Issue by OSFO** [Open-TEE/project#6]
Following the step by step instructions on a fairly untouched Ubuntu install for me renders in: 

`ERROR: /development/Open-TEE/emulator/internal_api/internal.qbs:3:1 Product dependency 'OpenSSL' not found for profile 'gcc'.`

* The project.qbs search path looks fine: 
  `qbsSearchPaths: 'project/qbs'`

* Building the little OpenSSL module from `project/qbs/modules/OpenSSL` alone works fine and openssl is found.

* There were some some issues when performing the initial  repo sync - some commands returned 0 data.

**Comment by uberspot** [comment]
Can you also give your qbs version given with `qbs -h` ? 
Mine is 1.4.1 and the error started to appear after a qbs upgrade on my system if I recall correctly.

**Comment by OSFO** [comment]
hmmm yep seems to be not unlikely 

`qbs -h 
 qbs 1.5.0`

**Comment by mikatammi** [comment]
https://review.gerrithub.io/#/c/237221/

There is a patch for newer QBS versions such as 1.5. This might break backwards compatibility with QBS 1.4.0. One version of QBS had a bug which caused that it was not possible to use Probes inside Modules, and using "Product" as a module was suggested as a workaround. However now it seems that Depends {} -item will only include Module-items from qbs-search-path/modules directory in newer QBS versions.

**Comment by thinhlevinh** [comment]
Yes, I also got the same problem when run : 
qbs debug
/Open-TEE/emulator/internal_api/internal.qbs:3:1 Product dependency 'OpenSSL' not found for profile 'gcc'.

**Comment by uberspot** [comment]
Just tested the patch and it works fine for qbs 1.4.1.

**Comment by OSFO** [comment]
yep same here downgraded to 1.3.2 and works fine...

Thanks!

**Comment by thinhlevinh** [comment]
It worked with the patch for a new QBS
Thanks,Mikatammi

**Comment by brianmcgillion** [comment]
uberspot, can you +1 the patch and lets get it committed

**Comment by brianmcgillion** [comment]
https://review.gerrithub.io/#/c/237221/

merged in commit : https://github.com/Open-TEE/project/commit/fcaea1285efca79c2fe79434590b1089c3f492bc
