### ISSUE TITLE
Building Open-TEE in Ubuntu 14.04

### ISSUE THREAD

**Issue by targetnull** [Open-TEE/project#8]
I followed the [tutorial](http://open-tee.github.io/tutorial/) and installed gcc, clang and other tools. Everything seemed to be going on well until I found that there is no `opentee.conf` in `/etc` directory, so I created on myself and copied the example configuration(removed the tip, of course). It didn't give me any error as I went on, but there were some warnings when I run `qbs debug`.

However, I don't see the following processes after `ps waux |grep tee`
>brian 5738 0.0 0.0 97176 852 ? Sl 10:40 0:00 tee_manager
>brian 5739 0.0 0.0 25216 1144 ? S 10:40 0:00 tee_launcher

Anyone knows what I did wrong? As I see it, there are only two things that might have cause the problem:
>1. `/etc/opentee.conf` does not exist.
>2. the warnings when running `qbs debug`.

I did not get anything unusual other than these two.
Thanks in advance!

**Comment by uberspot** [comment]
Could you paste your /etc/opentee.conf? 
It should be based on this btw https://github.com/Open-TEE/project/blob/master/opentee.conf

**Comment by targetnull** [comment]
It only consists of four lines
>ta_dir_path = $HOME/Open-TEE/gcc-debug/TAs
>core_lib_path = $HOME/Open-TEE/gcc-debug
>subprocess_manager = libManagerApi.so
>subprocess_launcher = libLauncherApi.so

There is not directory named `opentee_bin`, could you please tell me how to build it?

**Comment by uberspot** [comment]
Just add a line with the full path to your opentee binary. In this case it should be `$HOME/Open-TEE/gcc-debug/opentee-engine`. 
Also I guess you don't have `$HOME` in the config file but the actual `/home/someuser/` directory. Open-TEE doesn't translate the environmental variable `$HOME`.

**Comment by targetnull** [comment]
Yes, I replaced the /home/myname, I had thought it would be OK.
I delete the whole projec and plan to  restart over again. Hope it will work this time.
Thanks a lot!

**Comment by brianmcgillion** [comment]
if you join the irc channel #opentee on freenode we can help to step through the issue

**Comment by targetnull** [comment]
Hi, uberspot

It still doesn't work. I followed exactly the instructions on the [tutotial](http://open-tee.github.io/tutorial/), is there any trick I ignored?
I'm using Ubuntu 14.04(64 bit) in VMWare, does your project only support a 32-bit system?

Thanks.

**Comment by xzr** [comment]
just to make sure, you have:

1) compiled
2) set opentee.conf
3) ran opentee-engine ?

Can you see anything in syslog when you try running it? sudo tail -f /var/log/syslog

**Comment by brianmcgillion** [comment]
also can you post the qbs errors

**Comment by targetnull** [comment]
Hi, @brianmcgillion ,

I tried to join the channel, but there seems to be somehthing with my network, it is so slow:(..
Actually I don't think I see any errors, only some warning such as
>/home/targetnull/Open-TEE/libtee_pkcs11/src/hal_gp.c:106:2: warning: missing initializer [-Wmissing-field-initializers].

**Comment by targetnull** [comment]
@xzr 
Here is part of the log I get
>Sep 15 09:42:02 ubuntu tee_launcher: /home/targetnull/Open-TEE/emulator/opentee-main/main.c:load_lib:172  Failed to load library, (null)/(null) : (null)/(null): cannot open shared object file: No such file or directory
>Sep 15 09:44:55 ubuntu dhclient: DHCPREQUEST of 192.168.74.133 on eth0 to 192.168.74.254 port 67
>Sep 15 09:44:55 ubuntu dhclient: DHCPACK of 192.168.74.133 from 192.168.74.254
>Sep 15 09:44:55 ubuntu dhclient: bound to 192.168.74.133 -- renewal in 717 seconds.
>Sep 15 09:53:23 ubuntu tee_manager: /home/targetnull/Open-TEE/emulator/opentee-main/main.c:load_lib:172  Failed to load library, (null)/(null) : (null)/(null): cannot open shared object file: No such file or directory
>Sep 15 09:53:23 ubuntu tee_launcher: /home/targetnull/Open-TEE/emulator/opentee-main/main.c:load_lib:172  Failed to load library, (null)/(null) : (null)/(null): cannot open shared object file: No such file or directory

Maybe something wrong with my `.conf` file?

**Comment by targetnull** [comment]
@brianmcgillion ,

The last few lines it shows when running `qbs debug` are as follows
>inking libsigneleton_ta.so
>compiling keep_alive_and_signeleton_ta.c
>linking libkeep_alive_and_signeleton_ta.so
>Build done for configuration gcc-debug.

It seems normal for me

**Comment by xzr** [comment]
Hmm, the compilation part looks fine.

Could you please post /etc/opentee.conf again?

Also make sure that your user has read rights on the config file (just a wild guess)?

core_lib_path should point to the folder where you have libManagerApi.so
and libLauncherApi.so after compiling

**Comment by targetnull** [comment]
Here is `/etc/opentee.conf`
>ta_dir_path = /home/targetnull/Open-TEE/gcc-debug/TAs
>core_lib_path = /home/targetnull/Open-TEE/gcc-debug
>opentee_bin = /home/targetnull/Open-TEE/gcc-debug/opentee-engine
>subprocess_manager = libManagerApi.so
>subprocess_launcher = libLauncherApi.so

And I think core_lib_path has pointed to the right place
>targetnull@ubuntu:~/Open-TEE/gcc-debug$ ls /home/targetnull/Open-TEE/gcc-debug | grep .so
>libCommonApi.so
>libInternalApi.so
>libLauncherApi.so
>libManagerApi.so
>libtee_pkcs11.so
>libtee.so

**Comment by targetnull** [comment]
@xzr 

Forgot to say that I have read rights on the config file
>-rw-r--r-- 1 root root 249 Sep 15 10:07 /etc/opentee.conf

**Comment by xzr** [comment]
Hmm sorry I'm out of ideas and I don't currently have access to a machine with Open-TEE. 

One thing you could still try is adding a trailing / to the paths (no idea if it matters, but worth a try)

I can check it tomorrow

**Comment by brianmcgillion** [comment]
it is failing to load libManagerApi.so and libLauncherApi.so.

can you pass "-c /etc/opentee.conf" when launching opentee.

**Comment by targetnull** [comment]
@xzr 
It's alright, you have offered great help already.

**Comment by targetnull** [comment]
@brianmcgillion 

It doesn't give me any error or warning, but it still doesn't work.

**Comment by brianmcgillion** [comment]
time to break out the big guns :) You can copy and paste all the gcc commands to see that you have all the fields populated 

#launch open tee in foreground through gdb
gdb --args opentee-engine -f

(gdb) break main.c:350
(gdb) break main.c:170
(gdb) run

# first stops at line 350
(gdb) x/s arguments.config_file
0x403548:	"/etc/opentee.conf"

(gdb) x/s control_params.opentee_conf->ta_dir_path
0x605280:	"/home/brian/code/ccpp/Open-TEE/gcc-debug/TAs"

(gdb) x/s control_params.opentee_conf->core_lib_path
0x6052c0:	"/home/brian/code/ccpp/Open-TEE/gcc-debug"

(gdb) x/s control_params.opentee_conf->subprocess_manager
0x605040:	"/home/brian/code/ccpp/Open-TEE/gcc-debug/libManagerApi.so"

# continue to the second break point
(gdb) c

(gdb) x/s path
0x605040:	"/home/brian/code/ccpp/Open-TEE/gcc-debug/libManagerApi.so"

**Comment by targetnull** [comment]
The Big gun has shot the trouble:)

As I run, `(gdb) x/s control_params.opentee_conf->ta_dir_path`, I get
>(gdb) x/s control_params.opentee_conf->ta_dir_path
>0x0:	 <Address 0x0 out of bounds>

Even if I `sudo chmod 777 /etc/opentee.conf`, it doesn't work. That's really strange. Maybe I'll have to reinstall my Ubuntu:(

**Comment by targetnull** [comment]
@brianmcgillion 

I now know what I did wrong, I ignored the `[PATHS]` in `/etc/opentee.conf`, which cause the `\<Address 0x0 out of bounds\>` problem. I had thought it represented the existing paths instead of a keyword, and I fixed it now.

However, those two processes still won't be show. Really sad....

**Comment by brianmcgillion** [comment]
hold off on the reinstall of Ubuntu, there should be an easier solution, it is not windows after all :)

can you add another break point

(gdb) break conf_parser.c:93

x/s tmp_conf->core_lib_path

x/s tmp_conf->subprocess_manager

Then step over the function and print them again.

I will be back in an hour or so

**Comment by brianmcgillion** [comment]
just saw your next comment, it is an ini file format so the [PATHS] is a section name.

 can you post the new output of tail -f /var/log/syslog

**Comment by targetnull** [comment]
@brianmcgillion 
Huh, it works now, finally!
Remember xzr telling me to try adding a trailing / to the paths? Since my mistake has been fixed, the trailing / has caused an `Not a directory`. After I delete it, I saw the two processes
>1000       4045  0.0  0.0  27288   948 ?        Sl   11:19   0:00 tee_manager     
>1000       4046  0.0  0.1  23084  1604 ?        S    11:19   0:00 tee_launcher

Thank you very much for your patience!

**Comment by targetnull** [comment]
@brianmcgillion @xzr @uberspot 

I want to thank you again for your great help and patience. It is a little bit annoying that I just can't get the right output. But you help me solve the problem step by step, and I've learned how to debug a project using gdb, and the way of troubleshooting. That's really helpful.

I have to admit that for a beginner, setup a project on his own is a little difficult even with the tutorial, but when it is finally done, the progress seems very interesting and meaningful.

Many thanks to all of you!
Zih Yang

**Comment by xzr** [comment]
Think we might want to review the tutorial a bit to make it slightly clearer. Good thing that you got it working!

**Comment by brianmcgillion** [comment]
great that you got it working !! We will have to make a debian package to make the installation easier
